version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # Install diart before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py